export {default as MailIcon} from './MailIcon'
export {default as LocationIcon} from './LocationIcon'
export {default as PhoneIcon} from './PhoneIcon'
export {default as TelegramIcon} from './TelegramIcon'
export {GithubIcon,GithubIconFill} from './GithubIcon'
export {default as FacebookIcon} from './FacebookIcon'
export {default as HoverIcon} from './HoverIcon'
export {default as LivedemoIcon} from './LivedemoIcon'
export {default as PortfolioIcon} from './PortfolioIcon'
export {default as Arrowicon} from './Arrowicon'
