export {default as MailIcon} from './MailIcon'
export {default as LocationIcon} from './LocationIcon'
export {default as PhoneIcon} from './PhoneIcon'
export {default as TelegramIcon} from './TelegramIcon'
export {default as GithubIcon} from './GithubIcon'
export {default as FacebookIcon} from './FacebookIcon'
export {default as HoverIcon} from './HoverIcon'
